#ifndef SETCONFFILE_GLOBAL_H
#define SETCONFFILE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SETCONFFILE_LIBRARY)
#  define SETCONFFILESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SETCONFFILESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SETCONFFILE_GLOBAL_H
